server.port=8080
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/course_arrange?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=a123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
mybatis.type-aliases-package=com.pxw.pojo
mybatis.mapper-locations=classpath*:mapper/*.xml
